version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing dependencies..."
  pre_build:
    commands:
      - echo "Pre-build phase..."
      - mvn clean install # Build the WAR file using Maven

  build:
    commands:
      - echo "Entering build phase..."
      - echo "Build started on $(date)"
      - mvn -f pom.xml compile
      - mvn -f pom.xml package

  post_build:
    commands:
      - echo "Post-build phase..."
artifacts:
  files:
    - 'appspec.yml'
    - 'scripts/restart_server.sh'
    - 'scripts/clean_tomcat.sh'
    - 'target/gym-gym.war'